code reworking is under way.
SeeTheLand/ProjectManagementSystem pull request #1
Opened 2020-09-09 11:09 UTC by SeeTheLand

2020-09-19 11:07 UTC, alex97po requested changes

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/dao/ExceptionDAO.java
> +public class ExceptionDAO extends RuntimeException {
Плохое название, это же класс искючения, а не ДАО. Переименуй на DaoException

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/dao/ExceptionDAO.java
> +    public ExceptionDAO(String message, SQLException e) {
Второй параметр SQLException e не передается и не используется, в нем нет смысла

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/dao/JdbcDeveloperDAO.java
> +    private final DataSource dataSource = new DataSource();
Убери `= new DataSource();` у тебя стоит `@RequiredArgsConstructor` у тебя это поле будет инициализироваться в конструкторе

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/dao/JdbcDeveloperDAO.java
> +            throw new ExceptionDAO("Error while adding element", e);
У тебя исключение ничего не говорит о причине. Просто выведется в консоль сообщение, что была ошибка, но не ясно, что именно. Как минимум `"Error while adding element. Cause: " + e.getMessage();`
Плюс перед исключением будет неплохо сделать logger.error также

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Project.java
> +    public Project(Long id, String name, int latest_release_date, int cost) {
latest_release_date - нарушение Java Code Convention

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Project.java
> +@RequiredArgsConstructor
Зачем эта аннотация?

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Project.java
> +@EqualsAndHashCode(exclude = {"id"})
Может наоборот как раз? `@EqualsAndHashCode(of = "id")`

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Project.java
> +    private Integer cost;
Для денег использовать только BigDecimal

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Project.java
> +    private Integer count;
Название поля не очень объясняет, что это за поле. Это количество чего?

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/dao/JdbcProjectDAO.java
> +            return salarySum;
Это все делается проще, без дополнительной переменной:
`if(rs.next()) { return rs.getInt("sum"); }`

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/dao/JdbcDeveloperDAO.java
> +public class JdbcDeveloperDAO implements DeveloperDAO {
Такие классы (которые просто реализация интерфейса с таким же названием) - DeveloperDAOImpl (implementation)

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Developer.java
> +    private int salary;
Должен быть BigDecimal

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Developer.java
>      private String gender;
Нужен enum

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Developer.java
> +@EqualsAndHashCode(exclude = {"id"})
Может наоборот как раз? @EqualsAndHashCode(of = "id")

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/domain/DevelopersProjects.java
> +    private Long project_id;
Нарушение Java Code Convention

2020-09-19 11:07 UTC, alex97po commented on src/main/java/com/dermentli/projectmanagementsystem/service/ProjectService.java
> +    public List<Project> getProjectsInPreparedFormat() { return jdbcProjectDAO.getProjectsInPreparedFormat(); }
Не в том формате возвращается, как просится в задаче. Нужно 3 поля, а там и id, и cost. Когда начнется Хибернейт - будет сложно, потому что ты в domain в классе (который станет сущностью) добавил поля, которых нет в таблице. Сущность - отображение таблицы, для этого запроса можно создать ProjectDTO с 3 нужными полями, и этот объект и возвращать.

2020-09-19 11:09 UTC, alex97po commented
Есть еще общая проблема в проекте - .gitignore неправильно настроен, например, папка .idea не должна была попасть в репозиторий. Из-за этого в МР попадают лишние файлы, что усложняет чтение.

2020-09-19 11:11 UTC, alex97po commented
Также я не нашел в проекте файл с инициализацией базы (в папке resources), поэтому не мог запустить и посмотреть

2020-09-28 13:47 UTC, SeeTheLand commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Project.java
> +@RequiredArgsConstructor
у меня нет такой

2020-09-28 13:50 UTC, SeeTheLand commented on src/main/java/com/dermentli/projectmanagementsystem/domain/Project.java
> +    private Integer count;
не нашел

2020-09-28 13:56 UTC, SeeTheLand commented on src/main/java/com/dermentli/projectmanagementsystem/dao/JdbcProjectDAO.java
> +            return salarySum;
поправил, с возвращением значения Optional<Integer>, иначе нужно null возвращать.

2020-09-28 14:17 UTC, merged